name: build

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.editorconfig'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.editorconfig'
      - '.gitignore'

concurrency:
  # Maximum of one running workflow per pull request source branch
  # or branch and run number combination (cancels old run if action is rerun)
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v2-

      - run: ./gradlew --no-daemon build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: versions/*/build/libs/*.jar
